Feature/templates
aalexandrov7/jobs2022 pull request #1
Opened 2022-08-10 10:02 UTC by aalexandrov7

Changed all file naming to .php
Created template files for header, footer, pagination, search-and-filter, search-tags
Changed all the headers and footers with template files
Created db-connect.php for database connection and validation
Separated the registration form from register.php to register-form.php
Updated the html in register-form.php to make the appropriate fields required, added names to the form fields, added upload button for logo and text field describing that it is a logo field
Created the logic for registration form:
- stripping the special characters from input field
- created validations for required fields to not be empty
- sanitized and email check if admin or normal user 
- validating password to include the specified 8 chars, upper letter, lower letter and special character
- changed the html for the password field to be type="password" 
- validating phone number and concatenating so that is is unified and written always with the same formatting in database
- validating the company website has to start with http:// or https://
- check for already existing email address
- check for logo file validation, allowed extensions for the files are  .jpg, .jpeg, .png
- creating new logo file after user submit as follows takes company name -> to_lower -> replace special character and spaces with '-' and add extension of the file. 
- created error tracking for the the process of registration. After submitting the form you will get error messages is something is wrong else it will send you to home screen with a message for successful registration
- created SESSION for user status [login], [email_address], [first_name], additionally checks if account is an admin, a company or normal user

Created error template file used in register and login
Created success template file to get displayed in index.php after successful login or registraion
Created the logic for login.php:
- changed the html for the password field to be type="password", give all fields names and also to the submit button
- stripping the special characters from input field
- created validations for required fields to not be empty
- error message on empty fields
- search in database for username and password match, error message on no match
- SESSION for [email_address], [first_name], [success] (success message to be displayed after redirect to index.php), [login] (login status after successful login), check if the user is admin, company or normal user, gives a SESSION for that status

Created logic for logout page:
- checks if there is a SESSION[login] and destroys it.

Created 3 navigation files for menu:
- nav-admin.php for the admin view of the menu only header // footer will be updated next time
- nav-logged-in.php for logged in users view of the menu
- nav-logged-out.php for users with no profile

2022-08-10 11:35 UTC, Neychok requested changes
Hey, I left some comments. Generally, congratz on the progress and thanks for the long PR description :bow: 

You should also put more effort in correctly formatting your code.

2022-08-10 11:35 UTC, Neychok commented on index.php
> +				<?php include 'success.php'; require_once('success.php'); ?>
Why do we include success.php twice here?

2022-08-10 11:35 UTC, Neychok commented on login.php
> +      $user_password = md5($user_password);
There is a better way to hash and verify the password in PHP:
[password_hash()](https://www.php.net/manual/en/function.password-hash.php)
[password_verify()](https://www.php.net/manual/en/function.password-verify.php)

2022-08-10 11:35 UTC, Neychok commented on login.php
> +      $user_password = md5($user_password);
Okay, this is going to be a bit advanced but the way you check your password may open up your site to timing attacks. You better go with the two functions above.

2022-08-10 11:35 UTC, Neychok commented on login.php
> +			var_dump($row);
We have a var_dump here

2022-08-10 11:35 UTC, Neychok commented on login.php
> +		while ($row = $results->fetch_row()) {
We are only fetching one row, you don't really need a loop here.

2022-08-10 11:35 UTC, Neychok commented on login.php
> +		while ($row = $results->fetch_row()) {
This may help you [https://stackoverflow.com/questions/14624509/single-result-from-database-using-mysqli](https://stackoverflow.com/questions/14624509/single-result-from-database-using-mysqli)

[fetch_assoc()](https://www.w3schools.com/php/func_mysqli_fetch_assoc.asp)

2022-08-10 11:35 UTC, Neychok commented on nav-admin.php
> +<?php  if(isset($_SESSION['admin_status']) && $_SESSION['admin_status'] == 1) : ?>
Hey, here's an advice.

Instead of wrapping your whole function/template/code in a IF you can directly short circuit it.
```suggestion
<?php
if ( ! isset( $_SESSION['admin_status'] ) ||  1 !== $_SESSION['admin_status'] ) {
    return;
}
```

2022-08-10 11:35 UTC, Neychok commented on nav-logged-in.php
> +<?php  if($_SESSION['login']) : ?>
Same thing here, you can directly exit out of the template if the user is not logged-in.
```suggestion
<?php 
if ( ! isset( $_SESSION['login'] ) ) {
    return;
}
?>
```

2022-08-10 11:35 UTC, Neychok commented on register-form.php
> +	  }
Here's another good practice. You should only use `else` if you really need it. In this case, you can do something like this:
```suggestion
          $is_admin = 0;
	  if ( preg_match( $email_pattern, $email_address ) ) {
		$is_admin = 1;
	  }
```

or even
```suggestion
$is_admin = preg_match( $email_pattern, $email_address ) ? 1 : 0 
```

2022-08-10 11:35 UTC, Neychok commented on success.php
> +if(isset($_SESSION['success'])) : ?>
This success message thing can be done a lot better. Instead of setting a SESSION variable, you can just redirect to the specific page with a GET parameter `success=true` and then only display the success message if you have this parameter in the URL.

2022-08-10 11:35 UTC, Neychok commented
Oh and there is a merge conflict with the master branch so make sure your branch is up-to-date with master.

2022-08-10 11:53 UTC, aalexandrov7 commented on db-connect.php
> +<div class="test-messeges"><?php // echo "Connected successfully"; ?></div>
Test

2022-08-10 12:22 UTC, aalexandrov7 commented on db-connect.php
> +$servername = "localhost";
File and definitions were created and updated

2022-08-10 12:23 UTC, aalexandrov7 commented on index.php
> +				<?php include 'success.php'; require_once('success.php'); ?>
Removed one

2022-08-10 13:21 UTC, aalexandrov7 commented on login.php
> +      $user_password = md5($user_password);
Was successful integrated and works in register and login

2022-08-10 13:23 UTC, aalexandrov7 commented on login.php
> +			var_dump($row);
This was used to debug and is now commented out. Will be removed completely at later stage.

2022-08-10 14:08 UTC, aalexandrov7 commented on login.php
> +		while ($row = $results->fetch_row()) {
I will sync with you for this question

2022-08-10 14:23 UTC, aalexandrov7 commented on nav-admin.php
> +<?php  if(isset($_SESSION['admin_status']) && $_SESSION['admin_status'] == 1) : ?>
fixed

2022-08-10 14:23 UTC, aalexandrov7 commented on nav-logged-in.php
> +<?php  if($_SESSION['login']) : ?>
fixed

2022-08-10 14:34 UTC, aalexandrov7 commented on login.php
> +		while ($row = $results->fetch_row()) {
fixed after sync

2022-08-10 14:35 UTC, aalexandrov7 commented on register-form.php
> +	  }
Fixed

2022-08-10 14:37 UTC, aalexandrov7 commented on success.php
> +if(isset($_SESSION['success'])) : ?>
will do this in a new release

2022-08-10 18:43 UTC, Neychok requested changes
You missed one thing from the last review and there are two new comments for you to look at.

I also saw that you didn't implement the success message logic we talked about but let's leave it for a later period. Feel free to create a task about it.

2022-08-11 08:37 UTC, aalexandrov7 commented on register-form.php
> +	  $_SESSION['user_id'] = $row[0];
Reworked to include mysqli_insert_id()

2022-08-11 19:56 UTC, Neychok approved these changes
Good job!

2022-08-11 19:56 UTC, merged